# serverless.yml


service: xc-serverless-example-gql

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: us-east-1

functions:
  app:
    handler: server/app.serverless
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      NODE_ENV: 'production'
